package com.socratica.controller;

import com.socratica.dto.DocumentReviewResponse;
import com.socratica.service.DocumentReviewService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

/**
 * REST controller for the Document Review feature.
 *
 * <p>Accepts file uploads (PDF, DOCX, PPTX, TXT) and returns a structured AI review
 * generated by Google Gemini via the Google Generative Language API.
 *
 * <p>Google stack:
 * <ul>
 *   <li>Gemini 2.5 Flash – document type detection and context-aware review</li>
 * </ul>
 */
@RestController
@RequestMapping("/api/ai/document-review")
@RequiredArgsConstructor
public class DocumentReviewController {

    private final DocumentReviewService documentReviewService;

    /**
     * Upload a document and receive a structured Gemini-powered review.
     *
     * @param file the document file (PDF, DOCX, PPTX, PPTX legacy, or plain text)
     * @return structured review with detected type, strengths, weaknesses, suggestions, scores
     */
    @PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<DocumentReviewResponse> reviewDocument(
            @RequestParam("file") MultipartFile file) {
        if (file.isEmpty()) {
            return ResponseEntity.badRequest().build();
        }
        DocumentReviewResponse review = documentReviewService.reviewDocument(file);
        return ResponseEntity.ok(review);
    }
}
